<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$error=null;
$next=(string)($_GET['next']??$_POST['next']??'/panel');
if(!preg_match('~^/[A-Za-z0-9_/?=&%.-]*$~',$next))$next='/panel';
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();$email=strtolower(trim((string)($_POST['email']??'')));$password=(string)($_POST['password']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$password==='')throw new InvalidArgumentException('ایمیل یا رمز عبور صحیح نیست.');$stmt=db()->prepare('SELECT id,password FROM users WHERE email=? LIMIT 1');$stmt->execute([$email]);$u=$stmt->fetch();if(!$u||!password_verify($password,$u['password']))throw new InvalidArgumentException('ایمیل یا رمز عبور صحیح نیست.');session_regenerate_id(true);$_SESSION['user_id']=(int)$u['id'];redirect($next);}catch(Throwable $e){$error=$e instanceof InvalidArgumentException?$e->getMessage():'ورود به حساب انجام نشد.';}}
function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ورود | کاداد کلاس</title><link rel="manifest" href="/assets/manifest.json"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><style>:root{--t:#101828;--m:#667085;--p:#635bff;--b:#e4e7ec}*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Vazirmatn,Tahoma,sans-serif;color:var(--t);background:linear-gradient(145deg,#f8f9ff,#eef2ff);display:grid;place-items:center;padding:24px}.wrap{width:min(440px,100%)}.brand{display:flex;justify-content:center;gap:10px;align-items:center;text-decoration:none;color:var(--t);font-weight:900;font-size:22px;margin-bottom:22px}.logo{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,#766cff,#5148e8)}.card{background:#fff;border:1px solid var(--b);border-radius:25px;padding:34px;box-shadow:0 24px 70px rgba(16,24,40,.1)}h1{margin:0 0 8px;font-size:28px}.intro{margin:0 0 24px;color:var(--m);line-height:1.9}.error{background:#fff1f2;color:#be123c;padding:11px 13px;border-radius:12px;margin-bottom:17px;font-size:13px}label{display:block;font-size:13px;font-weight:800;margin-bottom:7px}input{width:100%;height:52px;border:1px solid var(--b);border-radius:14px;padding:0 15px;font:inherit;margin-bottom:17px}button{width:100%;height:54px;border:0;border-radius:15px;background:linear-gradient(135deg,#6d63ff,#5148e8);color:#fff;font:800 16px Vazirmatn;cursor:pointer}.bottom{text-align:center;color:var(--m);font-size:13px}.bottom a{color:#5148e8;font-weight:800;text-decoration:none}.back{display:block;text-align:center;margin-top:18px;color:var(--m);font-size:13px;text-decoration:none}</style></head><body><div class="wrap"><a class="brand" href="/home"><span class="logo">ک</span><span>کاداد کلاس</span></a><main class="card"><h1>خوش برگشتی 👋</h1><p class="intro">برای ورود به کلاس‌ها، وارد حساب کاداد کلاس شو.</p><?php if($error):?><div class="error"><?=h($error)?></div><?php endif;?><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="next" value="<?=h($next)?>"><label>ایمیل</label><input name="email" type="email" autocomplete="email" required><label>رمز عبور</label><input name="password" type="password" autocomplete="current-password" required><button>ورود به حساب</button></form><p class="bottom">حساب نداری؟ <a href="/login/signup.php">ساخت حساب</a></p></main><a class="back" href="/home">← بازگشت</a></div></body></html>
