<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
$user = require_auth();
$code = strtoupper(trim((string)($_GET['code'] ?? '')));
if (!preg_match('/^[A-Z0-9]{4,32}$/', $code)) { http_response_code(404); exit('کلاس پیدا نشد.'); }
$stmt = db()->prepare('SELECT c.*,u.name AS teacher_name FROM classes c JOIN users u ON u.id=c.teacher_id WHERE c.room_code=? LIMIT 1');
$stmt->execute([$code]);
$class = $stmt->fetch();
if (!$class) { http_response_code(404); exit('کلاس پیدا نشد.'); }
if ($class['expires_at'] !== null && strtotime((string)$class['expires_at']) <= time()) { http_response_code(410); exit('زمان این کلاس تمام شده است.'); }
$stmt = db()->prepare("SELECT cp.user_id,cp.role,u.name FROM class_participants cp JOIN users u ON u.id=cp.user_id WHERE cp.class_id=? AND cp.left_at IS NULL ORDER BY CASE WHEN cp.role='teacher' THEN 0 ELSE 1 END,u.name");
$stmt->execute([(int)$class['id']]);
$participants = $stmt->fetchAll();
$member = (int)$class['teacher_id'] === (int)$user['id'];
foreach ($participants as $p) if ((int)$p['user_id'] === (int)$user['id']) $member = true;
if (!$member) { http_response_code(403); exit('ابتدا باید با کد کلاس وارد شوید.'); }
function h(string $v): string { return htmlspecialchars($v, ENT_QUOTES, 'UTF-8'); }
?><!doctype html>
<html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1020"><title><?=h($class['title'])?> | کاداد کلاس</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}body{margin:0;height:100vh;overflow:hidden;background:#080d1b;color:#f8fafc;font-family:Vazirmatn,Tahoma,sans-serif}.top{height:70px;background:#0b1120;border-bottom:1px solid #26324a;display:flex;align-items:center;justify-content:space-between;padding:0 22px}.title{display:flex;align-items:center;gap:12px}.logo{width:40px;height:40px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#766cff,#5148e8);font-weight:900}.title strong{font-size:16px}.title small{display:block;color:#98a5bb;font-size:11px;margin-top:2px}.exit{color:#fff;text-decoration:none;background:#1c2639;border:1px solid #26324a;padding:9px 13px;border-radius:10px;font-size:12px;font-weight:800}.layout{height:calc(100vh - 70px);display:grid;grid-template-columns:minmax(0,1fr) 330px}.stage{padding:22px;display:flex;flex-direction:column;gap:16px;min-width:0}.notice{background:#10182a;border:1px solid #26324a;border-radius:18px;padding:18px}.notice h1{font-size:21px;margin:0 0 6px}.notice p{margin:0;color:#98a5bb;font-size:13px;line-height:1.9}.media{flex:1;min-height:300px;border:1px dashed #33415e;border-radius:22px;background:radial-gradient(circle at 50% 40%,#16223a,#0c1323 65%);display:grid;place-items:center;text-align:center}.media .icon{font-size:44px}.media h2{margin:10px 0 6px;font-size:18px}.media p{margin:0;color:#98a5bb;font-size:13px}.side{border-right:1px solid #26324a;background:#10182a;display:flex;flex-direction:column;min-height:0}.side-head{padding:18px 20px;border-bottom:1px solid #26324a}.side-head h2{margin:0;font-size:16px}.count{color:#98a5bb;font-size:12px;margin-top:4px}.people{padding:10px 14px;overflow:auto;max-height:34%}.person{display:flex;align-items:center;gap:10px;padding:9px 5px}.avatar{width:35px;height:35px;border-radius:50%;background:#202c45;display:grid;place-items:center;font-weight:900}.person-name{font-size:13px;font-weight:700;flex:1}.tag{font-size:10px;color:#aaa4ff;background:#252043;padding:4px 7px;border-radius:7px}.chat{border-top:1px solid #26324a;display:flex;flex-direction:column;min-height:0;flex:1}.chat-head{padding:14px 20px;font-weight:800;font-size:14px}.messages{flex:1;overflow:auto;padding:0 16px}.msg{padding:8px 0;border-bottom:1px solid rgba(38,50,74,.5)}.msg b{font-size:12px}.msg span{display:block;color:#d3d9e5;font-size:12px;margin-top:3px;line-height:1.7}.send{display:flex;gap:8px;padding:12px;border-top:1px solid #26324a}.send input{flex:1;min-width:0;background:#0c1323;color:#fff;border:1px solid #26324a;border-radius:10px;padding:10px;font:inherit}.send button{border:0;background:#756cff;color:#fff;border-radius:10px;padding:0 15px;font:800 12px Vazirmatn;cursor:pointer}@media(max-width:800px){body{overflow:auto;height:auto}.layout{height:auto;display:block}.stage{min-height:65vh}.side{min-height:500px;border-right:0;border-top:1px solid #26324a}.people{max-height:240px}.media{min-height:300px}}
</style></head><body><header class="top"><div class="title"><div class="logo">ک</div><div><strong><?=h($class['title'])?></strong><small>مدرس: <?=h($class['teacher_name'])?> · کد <?=h($class['room_code'])?></small></div></div><a class="exit" href="/panel">خروج از کلاس</a></header><main class="layout"><section class="stage"><div class="notice"><h1>کلاس آماده است 🎓</h1><p>در این مرحله تصویر و صدا عمداً غیرفعال است. اطلاعات کلاس، افراد حاضر و چت در دسترس‌اند.</p></div><div class="media"><div><div class="icon">🎥</div><h2>تصویر و صدا فعلاً غیرفعال است</h2><p>در مرحله بعد دوربین، میکروفون و RealtimeKit را اضافه می‌کنیم.</p></div></div></section><aside class="side"><div class="side-head"><h2>افراد کلاس</h2><div class="count"><?=count($participants)?> نفر حاضر</div></div><div class="people"><?php foreach($participants as $p): ?><div class="person"><div class="avatar"><?=h(mb_substr($p['name'],0,1))?></div><div class="person-name"><?=h($p['name'])?></div><?php if($p['role']==='teacher'): ?><span class="tag">مدرس</span><?php endif; ?></div><?php endforeach; ?></div><div class="chat"><div class="chat-head">چت کلاس 💬</div><div class="messages" id="messages"></div><form class="send" id="chatForm"><input id="message" maxlength="1000" placeholder="پیام خودت را بنویس..." autocomplete="off"><button>ارسال</button></form></div></aside></main><script>const classId=<?=json_encode((int)$class['id'])?>,messages=document.getElementById('messages'),input=document.getElementById('message');function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}async function loadChat(){try{const r=await fetch('/room/chat.php?class_id='+classId,{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();messages.innerHTML=d.messages.map(m=>'<div class="msg"><b>'+esc(m.name)+'</b><span>'+esc(m.message)+'</span></div>').join('');messages.scrollTop=messages.scrollHeight}catch(e){}}document.getElementById('chatForm').addEventListener('submit',async e=>{e.preventDefault();const t=input.value.trim();if(!t)return;const f=new FormData();f.append('class_id',classId);f.append('message',t);const r=await fetch('/room/chat.php',{method:'POST',body:f,credentials:'same-origin'});if(r.ok){input.value='';loadChat()}});loadChat();setInterval(loadChat,3000);</script></body></html>
