<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_auth();
$code = strtoupper(trim((string)($_GET['code'] ?? '')));
if (!preg_match('/^[A-Z0-9]{4,32}$/', $code)) { http_response_code(404); exit('کلاس پیدا نشد.'); }
$pdo=db(); $q=$pdo->prepare('SELECT c.*,u.name AS teacher_name FROM classes c JOIN users u ON u.id=c.teacher_id WHERE c.room_code=? LIMIT 1'); $q->execute([$code]); $class=$q->fetch();
if(!$class){http_response_code(404);exit('کلاس پیدا نشد.');}
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($class['title'],ENT_QUOTES,'UTF-8')?> | کلاس زنده</title><style>html,body{margin:0;height:100%;background:#080d1b;color:#fff;font-family:Tahoma,Arial,sans-serif}#meeting{width:100%;height:100%}.loading{height:100%;display:grid;place-items:center;text-align:center;color:#b8c2d4}.box{max-width:520px;padding:30px}.err{margin-top:15px;background:#3a1620;border:1px solid #713044;padding:14px;border-radius:12px;color:#ffd8e0;line-height:1.8}</style><script type="module">import{defineCustomElements}from'https://cdn.jsdelivr.net/npm/@cloudflare/realtimekit-ui@latest/loader/index.es2017.js';defineCustomElements();</script><script src="https://cdn.jsdelivr.net/npm/@cloudflare/realtimekit@latest/dist/browser.js"></script></head><body><div id="meeting"><div class="loading"><div class="box"><h2>در حال اتصال به کلاس 🎥</h2><p>در حال آماده‌سازی دوربین و میکروفون...</p><div id="error"></div></div></div></div><script>(async()=>{const error=document.getElementById('error');try{const r=await fetch('/realtime/token.php?class_id=<?= (int)$class['id'] ?>',{credentials:'same-origin'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'خطا در دریافت دسترسی');const meeting=await RealtimeKitClient.init({authToken:d.token,defaults:{audio:true,video:true}});const el=document.getElementById('meeting');el.innerHTML='<rtk-meeting id="rtk" show-setup-screen="true"></rtk-meeting>';document.getElementById('rtk').meeting=meeting;await meeting.join();}catch(e){error.innerHTML='<div class="err">'+String(e.message||e)+'</div>'}})();</script></body></html>
