(()=>{
'use strict';
const api='/ads/api.php';
let popupShown=false;
const css=`#kadad-ad5{position:fixed;inset:0;background:rgba(0,0,0,.82);z-index:99990;display:grid;place-items:center}#kadad-ad5 .box{width:min(900px,92vw);background:#08111f;border:1px solid #263650;border-radius:18px;overflow:hidden;box-shadow:0 25px 80px rgba(0,0,0,.45);position:relative}#kadad-ad5 .label{position:absolute;top:10px;right:10px;background:rgba(0,0,0,.65);color:#fff;padding:5px 8px;border-radius:8px;font:700 11px Tahoma;z-index:2}#kadad-ad5 video{width:100%;max-height:72vh;display:block;background:#000}#kadad-ad5 .count{position:absolute;left:10px;top:10px;background:rgba(0,0,0,.65);color:#fff;padding:5px 8px;border-radius:8px;font:700 11px Tahoma;z-index:2}#kadad-popup{position:fixed;left:18px;bottom:18px;width:min(360px,calc(100vw - 36px));z-index:99980;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 18px 60px rgba(0,0,0,.35);display:block}#kadad-popup .x{position:absolute;right:8px;top:8px;width:30px;height:30px;border:0;border-radius:50%;background:rgba(0,0,0,.65);color:#fff;cursor:pointer;z-index:2;font-size:18px}#kadad-popup img,#kadad-popup video{display:block;width:100%;max-height:360px;object-fit:cover}#kadad-popup .tag{padding:8px 10px;color:#344054;font:700 11px Tahoma;text-align:center}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const makeMedia=(ad,autoplay=false)=>{if(!ad)return null;let e;if(ad.type==='video'){e=document.createElement('video');e.src=ad.url;e.autoplay=autoplay;e.muted=true;e.playsInline=true;e.controls=false;}else{e=document.createElement('img');e.src=ad.url;e.alt='تبلیغ';}return e;};
const showFive=ad=>new Promise(resolve=>{if(!ad)return resolve();const o=document.createElement('div');o.id='kadad-ad5';o.innerHTML='<div class="box"><span class="label">تبلیغ</span><span class="count">۵ ثانیه</span></div>';const media=makeMedia(ad,true);if(media)o.querySelector('.box').appendChild(media);document.body.appendChild(o);let done=false;const finish=()=>{if(done)return;done=true;o.remove();resolve();};setTimeout(finish,5000);if(media&&media.tagName==='VIDEO'){media.onended=finish;media.play().catch(()=>{});}});
const showPopup=ad=>{if(!ad||popupShown)return;popupShown=true;const o=document.createElement('div');o.id='kadad-popup';const x=document.createElement('button');x.className='x';x.textContent='×';x.onclick=()=>o.remove();o.appendChild(x);const media=makeMedia(ad,false);if(media){if(media.tagName==='VIDEO'){media.autoplay=true;media.loop=true;media.muted=true;media.playsInline=true;media.controls=true;}o.appendChild(media);media.play?.().catch(()=>{});}const tag=document.createElement('div');tag.className='tag';tag.textContent='تبلیغ';o.appendChild(tag);document.body.appendChild(o);setTimeout(()=>o.remove(),15000);};
fetch(api,{credentials:'same-origin',cache:'no-store'}).then(r=>r.ok?r.json():null).then(async d=>{if(!d?.ok)return;await showFive(d.five_seconds);showPopup(d.popup);}).catch(()=>{});
})();
